[package]
name = "schema"
version.workspace = true
edition.workspace = true

[dependencies]
sqlx = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
schemars = { workspace = true }
