[package]
name = "app_state"
version.workspace = true
edition.workspace = true

[dependencies]
sqlx = { workspace = true }
adk-rust  = { workspace = true }
adk-runner = { workspace = true }
app_config = { workspace = true }
deadpool-redis = { workspace = true }
